### ISSUE TITLE
Can you share the unity asserts, source code？

### ISSUE THREAD

**Issue by grassofsky** [Rufus31415/react-webgl-3d-viewer-demo#2]
Can you share unity asserts, and i am learning how to use unity to develop webgl app with react.

Your work is great！

**Comment by Rufus31415** [comment]
In fact I compiled my app with Unity in WebGL and I used this npm package : https://www.npmjs.com/package/react-webgl
Are you more interested in my 3D model loader or just the integration of a Unity app in react?

**Comment by grassofsky** [comment]
I am more interested in your 3D model loader. I am amazed with such many formats supported.

**Comment by Rufus31415** [comment]
Ok cool !
Why not making it a react component available on npm, I've had this idea for a while. I'll look at it soon
(Did you see you can enter AR or VR to see your model in immersive on WebXR compatible browsers ;) ? )
