### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by lucaskmiyazaki** [Rufus31415/react-webgl-3d-viewer-demo#3]
I tried to yarn start and yarn build but it didn't work. I also tried react-app-rewired start and react-app-rewired build. How can I run it in development and how to build the production file?

**Comment by lucaskmiyazaki** [comment]
This is what I get
`yarn start
yarn run v1.22.5
$ react-app-rewired start
/bin/sh: 1: react-app-rewired: not found
error Command failed with exit code 127.`

**Comment by Rufus31415** [comment]
Here is a scenario that works on Windows 10 :
- Clone the repo
- run ```npm install```
- run ```npm start```

It seems your are on Linux, does it work ?

**Comment by lucaskmiyazaki** [comment]
it worked, thank you very much. I am sorry I am not very familiar with react and npm.
